// Generated by https://quicktype.io

export interface TypeTodosLosNumeros {
  message: string;
  data: Data;
  todosLosNumerosEver: string[];
}

export interface Data {
  tiposorteo: Tiposorteo[];
}

export interface Tiposorteo {
  titulo: string;
  numeros: Numero[];
}

export interface Numero {
  fecha: string;
  numero: string;
  numeros: string;
}
