// Generated by https://quicktype.io

export interface RespuestaDetalleSorteo {
  message: string;
  data: DatosSorteo;
}

export interface DatosSorteo {
  infoSorteo: InfoSorteo[];
  resultados: Resultado[];
}

export interface InfoSorteo {
  numero: string;
  titulo: string;
  fecha: string;
  link: string;
}

export interface Resultado {
  titulo: string;
  numeros: string;
  premios: Premio[];
}

export interface Premio {
  aciertos: string;
  ganadores: string;
  premio: string;
}

export interface TipoAciertos {
  res1: number; // tradicional
  res2: number; // la segunda
  res3: number; // revancha
  res4: number; // siempre sale
  res5: number; // pozo extra
}

export interface numerosIngresados {
  n1: number | string;
  n2: number | string;
  n3: number | string;
  n4: number | string;
  n5: number | string;
  n6: number | string;
}

export interface TipoBoleta {
  n1: number;
  n2: number;
  n3: number;
  n4: number;
  n5: number;
  n6: number;
}
