// Generated by https://quicktype.io

export interface RespuestaSorteos {
  message: string;
  cantidad: number;
  data: Sorteo[];
}

export interface Sorteo {
  sorteo: DatosSorteo;
}

export interface DatosSorteo {
  numero: string;
  titulo: string;
  fecha: string;
  link: string;
}
